### ISSUE TITLE
Suggestion to add certain commands

### ISSUE THREAD

**Issue by yaksit** [Bletch1971/PixelmonInformation#10]
Is there any way you can add other things from the "Pixelmon Extras" sidemod on reforged? (Most importantly EVs, IVs, and Hidden Power checks) This is a big request but it would be really cool if you added it, it would be really useful. The reason I ask is because the server hosting site me and my friends use, Aternos, doesn't allow for mods not on curseforge. I don't know how hard this is for you to add, but it would be so extremely helpful if you could. 

It would also be useful if you could add something like a command to hatch pokemon eggs instantaneously because sometimes eggs are bugged on the server as well.

These commands would look like:

/evs [name] [slot]
/ivs [name] [slot]
/hp [name] [slot]
/hatch [name] [slot]

These commands shouldn't be to hard to implement, you could essentially copy or recreate code from the mod "PixelmonExtras" on the Pixelmon Reforged site to just implement these, also if it's easier, commands aren't needed, you could add this into summaries and such. This would IMMENSELY helpful, so thank you very much for reading and hopefully implementing!

**Comment by Bletch1971** [comment]
I have finished implementing the EV and IV stats in WAILA and The One Probe.

In order to view the details for a part pokemon, select it and release it into the world. You can also view them for wild pokemon.

The HP is already available, just release your pokemon to view.

That is all I am going to add for this request.
